import React, { useState, useEffect, useCallback } from 'react';
import { View, Text, StyleSheet, SafeAreaView, ScrollView, TouchableOpacity, Alert, ActivityIndicator, RefreshControl } from 'react-native';
import { Activity, MessageSquare, Paperclip, ChevronDown, ChevronUp, Download, FileText } from 'lucide-react-native';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { getRecords, getCurrentUser } from '../../services/api';
import { useTheme } from '../../services/theme';
import { useTranslation } from 'react-i18next';

// Live data only
function getInitials(firstName: string, lastName: string) {
  return `${(firstName || '').replace('Dr. ', '').charAt(0)}${(lastName || '').charAt(0)}`.toUpperCase();
}

function formatDate(dateStr: string) {
  return new Date(dateStr).toISOString().split('T')[0];
}

const AVATAR_COLORS = ['#ffedd5', '#fef3c7', '#e0f2fe', '#fce7f3', '#dcfce7'];
const TEXT_COLORS = ['#c2410c', '#92400e', '#0369a1', '#be185d', '#166534'];

export default function RecordsScreen() {
  const [records, setRecords] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  const [expandedId, setExpandedId] = useState<number | null>(null);
  const { colors, dark } = useTheme();
  const { t } = useTranslation();

  const fetchData = useCallback(async () => {
    try {
      const data = await getRecords();
      if (Array.isArray(data) && data.length > 0) {
        setRecords(data);
      } else {
        setRecords([]);
      }
    } catch {
      setRecords([]);
    } finally {
      setLoading(false);
      setRefreshing(false);
    }
  }, []);

  useEffect(() => {
    fetchData();
  }, [fetchData]);

  const onRefresh = useCallback(() => {
    setRefreshing(true);
    fetchData();
  }, [fetchData]);

  const toggleExpand = (id: number) => {
    setExpandedId(prev => prev === id ? null : id);
  };

  const handleAttachment = (filename: string) => {
    Alert.alert(
      t('records.open_attachment'),
      t('records.download_prompt'),
      [
        { text: t('common.cancel'), style: 'cancel' },
        {
          text: t('records.download_label'),
          onPress: () => Alert.alert(t('records.downloaded'), t('records.downloaded_sub')),
        },
      ]
    );
  };

  const handleDownloadPdf = async (record: any) => {
    try {
      const doctorName = `Dr. ${record.doctor?.firstName || ''} ${record.doctor?.lastName || ''}`;
      const currentUser = getCurrentUser();
      const patientName = `${currentUser?.firstName || ''} ${currentUser?.lastName || ''}`.trim() || 'Patient';
      const date = formatDate(record.createdAt || record.date || '');
      
      const html = `
        <html>
          <head>
            <style>
              @page { margin: 0; }
              body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; padding: 40px; margin: 20px; color: #333; }
              .header { text-align: center; border-bottom: 2px solid #1E63D3; padding-bottom: 20px; margin-bottom: 30px; }
              .title { font-size: 28px; color: #1E63D3; margin: 0; }
              .subtitle { font-size: 14px; color: #666; margin-top: 5px; }
              .details { display: flex; justify-content: space-between; margin-bottom: 40px; background: #f8fafc; padding: 20px; border-radius: 8px; }
              .section { margin-bottom: 30px; }
              .section-title { font-size: 18px; color: #1E63D3; border-bottom: 1px solid #eee; padding-bottom: 8px; margin-bottom: 15px; }
              .content { font-size: 15px; line-height: 1.6; color: #444; }
              .footer { margin-top: 60px; font-size: 12px; text-align: center; color: #999; }
            </style>
          </head>
          <body>
            <div class="header">
              <h1 class="title">ClinicUz Medical Record</h1>
              <p class="subtitle">Official Patient Diagnostic Report</p>
            </div>
            
            <div class="details">
              <div>
                <strong>Attending Physician:</strong><br/>
                ${doctorName}
              </div>
              <div style="text-align: right">
                <strong>Date of Visit:</strong><br/>
                ${date}
              </div>
            </div>

            <div class="section">
              <h2 class="section-title">Clinical Diagnosis & Symptoms</h2>
              <div class="content">${record.diagnosis ? record.diagnosis.replace(/\n/g, '<br/>') : 'No diagnosis marked.'}</div>
            </div>

            ${record.notes ? `
            <div class="section">
              <h2 class="section-title">Prescriptions & Doctor's Suggestions</h2>
              <div class="content">${record.notes.replace(/\n/g, '<br/>')}</div>
            </div>
            ` : ''}

            <div class="footer">
              Patient: ${patientName} <br/>
              This document was securely generated by the ClinicUz Healthcare System.<br/>
              © ${new Date().getFullYear()} NavbatUz
            </div>
          </body>
        </html>
      `;
      
      const { uri } = await Print.printToFileAsync({ html, base64: false });
      if (await Sharing.isAvailableAsync()) {
        await Sharing.shareAsync(uri, { dialogTitle: t('records.download_pdf'), UTI: 'com.adobe.pdf', mimeType: 'application/pdf' });
      } else {
        Alert.alert(t('common.error'), t('records.share_error'));
      }
    } catch (e: any) {
      Alert.alert(t('records.download_failed'), e.message);
    }
  };

  if (loading) {
    return (
      <SafeAreaView style={[styles.container, { justifyContent: 'center', alignItems: 'center' }]}>
        <ActivityIndicator size="large" color="#1E63D3" />
        <Text style={{ marginTop: 12, color: '#64748B' }}>{t('records.loading')}</Text>
      </SafeAreaView>
    );
  }

  return (
    <SafeAreaView style={[styles.container, { backgroundColor: colors.background }]}>
      <View style={styles.header}>
        <Text style={[styles.headerTitle, { color: colors.text }]}>{t('records.title')}</Text>
        <Text style={[styles.headerSubtitle, { color: colors.textSecondary }]}>{records.length} {records.length !== 1 ? t('records.records_count_many') : t('records.records_count_one')}</Text>
      </View>

      <ScrollView
        contentContainerStyle={styles.listContainer}
        showsVerticalScrollIndicator={false}
        refreshControl={<RefreshControl refreshing={refreshing} onRefresh={onRefresh} colors={[colors.primary]} />}
      >
        {records.length === 0 ? (
          <View style={styles.emptyState}>
            <Activity color={colors.textSecondary} size={48} />
            <Text style={[styles.emptyTitle, { color: colors.textSecondary }]}>{t('records.no_records')}</Text>
            <Text style={[styles.emptySubtitle, { color: colors.textSecondary }]}>{t('records.no_records_sub')}</Text>
          </View>
        ) : (
          records.map((record, index) => {
            const doctor = record.doctor || {};
            const initials = getInitials(doctor.firstName || '', doctor.lastName || '');
            const bg = AVATAR_COLORS[index % AVATAR_COLORS.length];
            const color = TEXT_COLORS[index % TEXT_COLORS.length];
            const date = formatDate(record.createdAt || record.date || '');
            const isExpanded = expandedId === record.id;
            const prescriptions = record.prescriptions || [];
            const attachments = record.attachments || [];

            return (
              <View key={record.id} style={[styles.card, { backgroundColor: colors.card, borderColor: colors.border }]}>
                
                {/* Doctor Info Row - Tappable to expand */}
                <TouchableOpacity style={styles.doctorRow} onPress={() => toggleExpand(record.id)}>
                  <View style={[styles.avatar, { backgroundColor: bg }]}>
                    <Text style={[styles.avatarText, { color }]}>{initials}</Text>
                  </View>
                  <View style={styles.doctorInfo}>
                    <Text style={[styles.doctorName, { color: colors.text }]}>{doctor.firstName} {doctor.lastName}</Text>
                    <Text style={[styles.recordDate, { color: colors.textSecondary }]}>{date}</Text>
                  </View>
                  {isExpanded
                    ? <ChevronUp color={colors.textSecondary} size={20} />
                    : <ChevronDown color={colors.textSecondary} size={20} />
                  }
                </TouchableOpacity>

                {/* Diagnosis Section - Always visible */}
                <View style={styles.diagnosisSection}>
                  <View style={[styles.pulseIconContainer, { backgroundColor: dark ? '#1E3A5F' : '#EFF6FF' }]}>
                    <Activity color={colors.primary} size={20} />
                  </View>
                  <View>
                    <Text style={[styles.sectionLabelTxt, { color: colors.textSecondary }]}>{t('records.diagnosis')}</Text>
                    <Text style={[styles.diagnosisTitle, { color: colors.text }]}>{record.diagnosis}</Text>
                  </View>
                </View>

                {/* Expanded Content */}
                {isExpanded && (
                  <>
                    {/* Prescriptions Section */}
                    {prescriptions.length > 0 && (
                      <View style={styles.prescriptionsSection}>
                        <Text style={[styles.sectionLabelTxt, { color: colors.textSecondary }]}>{t('records.prescriptions')}</Text>
                        <View style={styles.tagsContainer}>
                          {prescriptions.map((med: string, idx: number) => (
                            <TouchableOpacity
                              key={idx}
                              style={[styles.prescriptionPill, { backgroundColor: dark ? '#1E3A5F' : '#EFF6FF' }]}
                              onPress={() => Alert.alert('Prescription', `${med}\n\nTake as directed by your doctor.`)}
                            >
                              <Text style={[styles.prescriptionText, { color: dark ? '#93C5FD' : '#1E63D3' }]}>{med}</Text>
                            </TouchableOpacity>
                          ))}
                        </View>
                      </View>
                    )}

                    {/* Notes Section */}
                    {record.notes && (
                      <View style={styles.notesSection}>
                        <MessageSquare color={colors.textSecondary} size={16} style={{ marginTop: 2, marginRight: 8 }} />
                        <Text style={[styles.notesText, { color: colors.textSecondary }]}>{record.notes}</Text>
                      </View>
                    )}

                    {/* Attachments Section */}
                    {attachments.length > 0 && (
                      <View style={styles.attachmentsRow}>
                        {attachments.map((file: string, idx: number) => (
                          <TouchableOpacity
                            key={idx}
                            style={[styles.attachmentPill, { backgroundColor: dark ? '#1E3A5F' : '#EFF6FF', borderColor: dark ? '#1E40AF' : '#BFDBFE' }]}
                            onPress={() => handleAttachment(file)}
                          >
                            <Paperclip color={dark ? '#93C5FD' : '#1E63D3'} size={14} style={{ marginRight: 6 }} />
                            <Text style={[styles.attachmentText, { color: dark ? '#93C5FD' : '#1E63D3' }]}>{file}</Text>
                            <Download color={dark ? '#93C5FD' : '#1E63D3'} size={12} style={{ marginLeft: 6 }} />
                          </TouchableOpacity>
                        ))}
                      </View>
                    )}

                    {/* PDF Download Button */}
                    <TouchableOpacity style={[styles.shareBtn, { backgroundColor: '#1E63D3', flexDirection: 'row', justifyContent: 'center' }]} onPress={() => handleDownloadPdf(record)}>
                      <FileText color="#FFFFFF" size={18} style={{ marginRight: 8 }} />
                      <Text style={[styles.shareBtnText, { color: '#FFFFFF' }]}>{t('records.download_pdf')}</Text>
                    </TouchableOpacity>
                  </>
                )}
              </View>
            );
          })
        )}
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F8FAFC' },
  header: { padding: 20, paddingTop: 40, paddingBottom: 16 },
  headerTitle: { fontSize: 28, fontWeight: 'bold', color: '#111827' },
  headerSubtitle: { fontSize: 14, color: '#64748B', marginTop: 4 },
  listContainer: { padding: 20, gap: 16, paddingBottom: 100 },
  card: {
    backgroundColor: '#FFFFFF', borderRadius: 24, padding: 20,
    shadowColor: '#000', shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05, shadowRadius: 15, elevation: 2,
    borderWidth: 1, borderColor: '#F1F5F9'
  },
  doctorRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 20 },
  avatar: { width: 44, height: 44, borderRadius: 22, alignItems: 'center', justifyContent: 'center', marginRight: 16 },
  avatarText: { fontSize: 16, fontWeight: 'bold' },
  doctorInfo: { flex: 1, justifyContent: 'center' },
  doctorName: { fontSize: 16, fontWeight: 'bold', color: '#111827', marginBottom: 2 },
  recordDate: { fontSize: 14, color: '#64748B' },
  sectionLabelTxt: { fontSize: 12, color: '#9CA3AF', marginBottom: 4 },
  diagnosisSection: { flexDirection: 'row', alignItems: 'center', marginBottom: 16 },
  pulseIconContainer: {
    width: 36, height: 36, borderRadius: 12, backgroundColor: '#EFF6FF',
    alignItems: 'center', justifyContent: 'center', marginRight: 12
  },
  diagnosisTitle: { fontSize: 18, fontWeight: 'bold', color: '#111827' },
  prescriptionsSection: { marginBottom: 16 },
  tagsContainer: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 4 },
  prescriptionPill: {
    backgroundColor: '#EFF6FF', paddingHorizontal: 10, paddingVertical: 6, borderRadius: 6
  },
  prescriptionText: { fontSize: 13, color: '#1E63D3', fontWeight: '500' },
  notesSection: { flexDirection: 'row', alignItems: 'flex-start', marginBottom: 16 },
  notesText: { flex: 1, fontSize: 14, color: '#4B5563', lineHeight: 20 },
  attachmentsRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 16 },
  attachmentPill: {
    flexDirection: 'row', alignItems: 'center', backgroundColor: '#EFF6FF',
    paddingHorizontal: 12, paddingVertical: 8, borderRadius: 16, borderWidth: 1, borderColor: '#BFDBFE'
  },
  attachmentText: { fontSize: 13, color: '#1E63D3', fontWeight: '500' },
  shareBtn: {
    paddingVertical: 10, borderRadius: 12, backgroundColor: '#F1F5F9', alignItems: 'center',
  },
  shareBtnText: { fontSize: 14, fontWeight: '600', color: '#64748B' },
  emptyState: { alignItems: 'center', paddingVertical: 60 },
  emptyTitle: { fontSize: 18, fontWeight: 'bold', color: '#64748B', marginTop: 16, marginBottom: 8 },
  emptySubtitle: { fontSize: 14, color: '#9CA3AF', textAlign: 'center' },
});
